raw_data_dir: "MEGA/CHIPS_DATA"
output_dir: "MEGA"
manifest_bpm: "MEGA/mega_files/Multi-EthnicGlobal_D2.bpm"
manifest_csv: "MEGA/mega_files/Multi-EthnicGlobal_D2.csv"
clusterfile_egt: "MEGA/mega_files/Multi-EthnicGlobal_D1_ClusterFile.egt"
ref_genome: "MEGA/ref_genomes/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
stats_tsv_name: "SHS_Multi-EthnicGlobal_8_GRCh38.tsv"
vcf_gz_name: "SHS_Multi-EthnicGlobal_8_GRCh38.vcf.gz"
csi_name: "SHS_Multi-EthnicGlobal_8_GRCh38.vcf.gz.csi"
threads: 64